export { default as World } from './World/World'
export { default as Interface } from './Interface/Interface'  
export { default as About } from './pages/About'
export { default as Contact } from './pages/Contact'
export { default as Projects } from './pages/Projects/Projects'
export { default as Services } from './pages/Services'